dist: focal
arch: 
  - amd64
language: python
services:
  - docker
python:
- '3.10'
install:
- python -m pip install --upgrade pip
- curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile=minimal -y
- export PATH=${TRAVIS_HOME}/.cargo/bin:$PATH
- rustup update
- python -m pip install --upgrade pip
- cd python-bindings
- pip install -r requirements.txt
script:
- ./build.sh
before_deploy:
- python3 -m pip install --upgrade build
- pip install maturin
- echo $'[pypi]\nusername = __token__\npassword = '$PYPI_TOKEN > ~/.pypirc
deploy:
  - provider: script
    script:  maturin publish
    on:
      repo: TheCacophonyProject/cptv-tools
      tags: true
    skip_cleanup: 'true'
